### ISSUE TITLE
(migratus/create ...) returns true but does not create migration scripts

### ISSUE THREAD

**Issue by pate** [yogthos/migratus#71] opened 2016-05-13 09:27 UTC
When I call `(migratus/create config "my-migration")`, the function returns true, but does not create any .sql files. The first call worked, but subsequent attempts fail. I have restarted my REPL, with no luck.

Here is my config:

```
(def config {:store                :database
             :migration-dir        "migrations/"
             :migration-table-name "migrations"
             :db                   "postgresql://localhost:5432/test-db"})
```

My migrations folder lives at `~/resources/migrations`.

Why would migratus not create the new migration templates without an exception?

**Comment by yogthos** [comment] 2016-05-13 12:45
I can't see any reason why this wouldn't work repeatedly. The code for create is [here](https://github.com/yogthos/migratus/blob/80607fe35816352d94845bee81cbc4d7a77742b2/src/migratus/database.clj#L264) and all it does is call the `createNewFile` method on the new `File` object created using the migrations directory and the migration name.

Perhaps worth checking what `(:migration-dir config)` resolves to in the REPL. This is the code that looks for the migrations folder:

```clojure
(defn find-migration-dir [dir]
  (->> (cp/classpath-directories)
       (map #(io/file % dir))
       (filter #(.exists ^File %))
       first))

(def default-migration-parent
  "resources/")

(defn find-or-create-migration-dir [dir]
  (if-let [migration-dir (find-migration-dir dir)]
    migration-dir

    ;; Couldn't find the migration dir, create it
    (let [new-migration-dir (io/file default-migration-parent dir)]
      (io/make-parents new-migration-dir ".")
      new-migration-dir)))
```

**Comment by yogthos** [comment] 2016-10-27 03:17
I'm going to close this one as I'm unable to reproduce and there haven't been any other reports regarding this.

**Closed by yogthos** 2016-10-27 03:17 UTC
