### ISSUE TITLE
Validate the migration ids that are passed in

### ISSUE THREAD

**Issue by pjstadig** [yogthos/migratus#3] opened 2011-12-08 15:09 UTC

**Comment by ndrluis** [comment] 2016-06-24 01:45
what type of validations?

Verify the create date with the timestamp on filename?
Verify the filename has a correct timestamp pattern?

**Comment by yogthos** [comment] 2016-06-24 02:03
Looks like this might be done already. The [find-migration-files](https://github.com/yogthos/migratus/blob/77cfb6f9d3437b835bb5954b3f53a82f3a410bcc/src/migratus/database.clj#L117) function will warn if it's unable to parse the filename.

**Comment by jumarko** [comment] 2017-03-09 07:43
@yogthos not sure what @pjstadig meant by this by I can confirm that validation works for cases like "*-up.sql" (it should be "*.up.sql"). In that case, the error message is clear.

It there's no other reason to leave this issue open I suggest to close it.

**Comment by yogthos** [comment] 2017-03-09 13:55
sounds good to me

**Closed by yogthos** 2017-03-09 13:55 UTC
Labels: enhancement, help wanted
