### ISSUE TITLE
Attempting to roll back multiple migrations raises an exception

### ISSUE THREAD

**Issue by ricardojmendez** [yogthos/migratus#30] opened 2015-07-02 10:50 UTC
The [Luminus migratus documentation](http://www.luminusweb.net/docs/migrations.md) states that one can pass migration ids to rollback/migrate.  Attempting to do so with rollback raises an exception:

```
$ lein run rollback 20150702130104 20150702123955
Exception in thread "main" clojure.lang.ArityException: Wrong number of args (3) passed to: core/rollback, compiling:(/private/var/folders/64/ckdtdxm14059n9wh8rhf1mvw0000gn/T/form-init5872681998558105682.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7239)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: clojure.lang.ArityException: Wrong number of args (3) passed to: core/rollback
	at clojure.lang.AFn.throwArity(AFn.java:429)
	at clojure.lang.AFn.invoke(AFn.java:40)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:632)
	at appname.db.migrations$migrate.invoke(migrations.clj:17)
	at appname.core$_main.doInvoke(core.clj:37)
[...]
```

I haven't tried it with migrate to see if it does work on that case.

**Comment by yogthos** [comment] 2015-07-02 15:17
Looks like you might have an older template, with the latest you should see:

```
ls resources/migrations/
20150702111448-foo.down.sql           20150702111456-bar.down.sql           201507110555-add-users-table.down.sql
20150702111448-foo.up.sql             20150702111456-bar.up.sql             201507110555-add-users-table.up.sql
> lein run migrate 20150702111448 20150702111456 201507110555
Jul 02, 2015 11:16:25 AM clojure.tools.logging$eval464$fn__468 invoke
INFO: Starting migrations
Jul 02, 2015 11:16:25 AM clojure.tools.logging$eval464$fn__468 invoke
INFO: creating migration table 'schema_migrations'
Jul 02, 2015 11:16:25 AM clojure.tools.logging$eval464$fn__468 invoke
INFO: Ending migrations
```

**Comment by ricardojmendez** [comment] 2015-07-02 15:28
I might. Where would this be handled? On appname.db.migrations?  I've just created a new template but see barely any difference on that file.

**Comment by yogthos** [comment] 2015-07-02 15:36
The [migrations.clj](https://github.com/luminus-framework/luminus-template/blob/master/src/leiningen/new/luminus/db/src/migrations.clj) now expects multiple args and will use `(apply migratus/up config (rest args))` if there's additional arguments

**Comment by ricardojmendez** [comment] 2015-07-02 16:22
Odd. I see that file as being the same (haven't modified it), and I'm using 0.8.1 (just checked migratus.core against mine).  Will review further.

**Comment by yogthos** [comment] 2015-07-02 16:24
yeah that's a bit odd, let me know what you find

**Comment by yogthos** [comment] 2015-07-02 16:26
oh I think I see it, the problem is with rollback where I should be calling down

**Comment by yogthos** [comment] 2015-07-02 16:30
just pushed out the fix [here](https://github.com/luminus-framework/luminus-template/commit/881775ae41d57b9a86e9ff3b8739938645218188)

**Comment by ricardojmendez** [comment] 2015-07-02 16:41
That makes sense. :-) Testing, I no longer get an exception (since `down` does take the ids) but the migrations are not rolled back. Looking at the code, I should be seeing a log/info on `run-down`, but I'm getting none.

```
$ lein run rollback 20150702134153 20150702124509
(20150702134153 20150702124509)
Jul 02, 2015 7:35:42 PM clojure.tools.logging$eval18782$fn__18788 invoke
INFO: Starting migrations
Jul 02, 2015 7:35:42 PM clojure.tools.logging$eval18782$fn__18788 invoke
INFO: Ending migrations
```

Stupid question, since I'm only just getting familiar with migratus, but on [line 79](https://github.com/yogthos/migratus/blob/7155ede83c74ed0df7a527402af7f751e462231a/src/migratus/core.clj#L79) you do an intersection between the completed ids and the ones being received.

Could it be there's an intersection being done between the integer values being retrieved from the db, and the string ones received on args?

**Comment by yogthos** [comment] 2015-07-02 16:43
Oh that's a good catch, I think that's exactly what's happening there

**Comment by yogthos** [comment] 2015-07-02 16:47
this should work

```clojure
(defn parse-ids [args]
  (map (memfn Integer/parseInt) (rest args)))

(defn migrate [args]
  (let [config {:store :database
                :db {:connection-uri (:database-url env)}}]
    (case (first args)
      "migrate"
      (if (> (count args) 1)
        (apply migratus/up config (parse-ids args))
        (migratus/migrate config))
      "rollback"
      (if (> (count args) 1)
        (apply migratus/down config (parse-ids args))
        (migratus/rollback config)))))
```

**Comment by yogthos** [comment] 2015-07-02 16:54
err `Double/parseDouble`

**Comment by yogthos** [comment] 2015-07-02 16:59
nvm it's a long :)

**Comment by yogthos** [comment] 2015-07-02 17:01
ok tested locally and appears to be working now, I just pushed the [new fix](https://github.com/luminus-framework/luminus-template/commit/24c6ba870a29170b6888f181d74cadf189a53332) to clojars

**Comment by yogthos** [comment] 2015-07-02 19:53
sounds like we can close this one, it looks like it was a bug in luminus in any case so if it persists we should probably move the issue there

**Closed by yogthos** 2015-07-02 19:53 UTC

**Comment by ricardojmendez** [comment] 2015-07-02 20:52
Things are good on my end after applying the changes - we can leave it closed. Cheers!
