### ISSUE TITLE
Migratus doesn't find migrations in uberjar when built with deps.edn

### ISSUE THREAD

**Issue by pcolliander** [yogthos/migratus#184] opened 2020-05-09 08:20 UTC
Hi,

I migrated my project from using lein to clj-deps. After this change `migratus/migrate` no longer find new migrations. I verified this by building an uberjar with `lein` instead, and then it does find the migrations.

I'm using [uberdeps](https://github.com/tonsky/uberdeps) to build the uberjar with deps.edn. If I compare the uberjar built with lein and uberdeps I don't see any big differences:

built with deps.edn
```
migrations/2018110021231-x.sql
migrations/2018110021231-x.sql
```

built with leiningen
```
migrations/
migrations/2018110021231-x.sql
migrations/2018110021231-x.sql
```

Only difference I see is that there's a `migrations/` in the leiningen uberjar above the migrations.

```
; my deps.edn
; ---
:paths ["src/clj" "src/cljc" "resources" "classes"]
:aliases
           :uberjar {:extra-deps {uberdeps {:mvn/version "0.1.8"}}
                     :main-opts ["-m" "uberdeps.uberjar"]}
```

Is there something different I have to do with regards to migratus when building an uberjar with deps.edn instead of lein?

**Comment by yogthos** [comment] 2020-05-09 15:17
I don't use deps.edn myself, so unfortunately I don't know really know how the uberjar is created with uberdeps. It might be better to open an issue with the uberdeps project to see what's happening.

**Comment by skoestler** [comment] 2020-05-17 16:43
For what it's worth, I'm using https://github.com/seancorfield/depstar to build my uberjar and migratus seems to property find and run migrations.

**Comment by yogthos** [comment] 2020-05-18 04:09
Since migratus works with both leiningen and depstar, it seems like the issue is with uberdeps, so I'm going to close it.

**Closed by yogthos** 2020-05-18 04:09 UTC
Labels: enhancement, help wanted, question

**Comment by amackera** [comment] 2021-07-30 20:00
Anyone stumbling on this in modern times: just make sure you're running `uberdeps` >= 1.0.0 and it should work as expected
